name: paddle
channels:
- pytorch
- defaults
dependencies:
- numpy>=1.15
- pip>=10.0
- pytest>=3.0.7
- python>=3.6
- scikit-learn>=0.19.1
- scipy=1.0.0
- seaborn=0.9.0
- pytorch>=1.0
- pytorch-cpu
- torchvision
- networkx
- pip:
  - "--editable=git+https://github.com/openml/openml-python.git@a2b602b1c939d533d78956661e7771bcd2284d60#egg=openml-master"
